Style/IfUnlessModifier:
  MaxLineLength: 120

Style/LineLength:
  Max: 120

Style/WhileUntilModifier:
  MaxLineLength: 120

Style/AsciiComments:
  Enabled: false

Documentation:
  Enabled: false

AllCops:
  Includes:
    - Rakefile
    - Capfile
    - config.ru
  Excludes:
    - db/**
    - config/**
    - script/**
    - faye/**
